### ISSUE TITLE
ParseTransactionError: No such asset: ICEBLOOD

### ISSUE THREAD

**Issue by jdogresorg** [DogepartyXDP/dogeparty-lib#43]
dogeparty-lib is currently choking while parsing an issuance.

```
[2024-02-12 22:54:15][INFO] Block: 5087539 (5.78s, hashes: L:24f11 / TX:db963 / M:bce2f)
[2024-02-12 22:55:24][WARNING] ParseTransactionError for tx d1a2de9706704ac3ec13ee35c9de87c7d05b5c1059ae2ebbc20c6eb18802a4ba: No such asset: ICEBLOOD
[2024-02-12 22:55:24][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/dogeparty-lib/dogepartylib/lib/blocks.py", line 109, in parse_tx
    issuance.parse(db, tx, message, message_type_id)
  File "/dogeparty-lib/dogepartylib/lib/messages/issuance.py", line 470, in parse
    description = util.get_asset_description(db, asset)
  File "/dogeparty-lib/dogepartylib/lib/util.py", line 537, in get_asset_description
    if not issuances: raise exceptions.AssetError('No such asset: {}'.format(asset))
dogepartylib.lib.exceptions.AssetError: No such asset: ICEBLOOD

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dogeparty-server", line 11, in <module>
    load_entry_point('dogeparty-cli', 'console_scripts', 'dogeparty-server')()
  File "/dogeparty-cli/dogepartycli/__init__.py", line 16, in server_main
    server.main()
  File "/dogeparty-cli/dogepartycli/server.py", line 172, in main
    server.start_all(db)
  File "/dogeparty-lib/dogepartylib/server.py", line 494, in start_all
    blocks.follow(db)
  File "/dogeparty-lib/dogepartylib/lib/blocks.py", line 1477, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
  File "/dogeparty-lib/dogepartylib/lib/blocks.py", line 211, in parse_block
    raise e
  File "/dogeparty-lib/dogepartylib/lib/blocks.py", line 205, in parse_block
    parse_tx(db, tx)
  File "/dogeparty-lib/dogepartylib/lib/blocks.py", line 148, in parse_tx
    raise exceptions.ParseTransactionError("%s" % e)
dogepartylib.lib.exceptions.ParseTransactionError: No such asset: ICEBLOOD
```

**Comment by jdogresorg** [comment]
fixed in 9.62.1 release
